# Generated by Django 3.2.3 on 2021-05-30 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeMarca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeModelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('alvo', models.BooleanField(default=False)),
                ('militar', models.BooleanField(default=False)),
                ('policial', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDocumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProcedimento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeRelacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[A-Z]{3}[0-9][0-9A-Z][0-9]{2}', code='placainvalida', message='Formato de placa Inválido!')])),
                ('Ano', models.IntegerField()),
                ('Notas', models.TextField(blank=True, null=True)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alvos.marcaveiculo')),
                ('Modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alvos.modeloveiculo')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PessoaAte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoaate', to='alvos.pessoa')),
                ('PessoaDe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoade', to='alvos.pessoa')),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.tiporelacao')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numeracao', models.CharField(max_length=50, verbose_name='Numeração')),
                ('Nota', models.TextField(blank=True, null=True)),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
                ('TipoProcedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.tipoprocedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroOcorrencia', models.CharField(max_length=50)),
                ('Data', models.DateField(blank=True, null=True)),
                ('Dinamica', models.TextField(blank=True, null=True)),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMail', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator(code='emailinvalido', message='E-Mail inválido!')])),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.CharField(max_length=50)),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.tipodocumento')),
            ],
        ),
    ]
