# Generated by Django 3.2.3 on 2021-05-30 17:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alvos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('\\d{10,11}', code='telinfalido', message='Informe telefone no formato 2199998888, entre 10 e 11 dígitos')])),
                ('notas', models.TextField()),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeEntrada', models.CharField(max_length=255)),
                ('NomePossivelAlvo', models.CharField(blank=True, max_length=255, null=True)),
                ('NomeArquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('PossivelAlvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alvos.pessoa')),
                ('TelefoneRelacioando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.TextField()),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alvos.pessoa')),
            ],
        ),
    ]
