# Generated by Django 3.2.3 on 2021-07-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alvos', '0004_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='Arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
